from typing import TypedDict

from mcstatus.motd.components import Formatting, MinecraftColor


# fmt: off
class ColorInfo(TypedDict):
    """颜色信息类型提示"""
    name_en: str                        # 英文名称
    hex: str                            # 前景色十六进制
    dark_hex: str                       # 背景色十六进制
    rgb: tuple[int, int, int]           # 前景色 RGB 值
    dark_rgb: tuple[int, int, int]      # 背景色 RGB 值
    ansi: str                           # ANSI 转义序列
    bedrock: bool                       # 基岩版可用性
    java: bool                          # Java 版可用性
    code: str                           # Minecraft 格式代码（含 § 前缀）


class FormatInfo(TypedDict):
    """格式信息类型提示"""
    name_en: str             # 英文名称
    ansi: str                # ANSI 转义序列
    bedrock: bool            # 基岩版可用性
    java: bool               # Java 版可用性
    code: str                # Minecraft 格式代码（含 § 前缀）


# 颜色代码字典，使用 MinecraftColor 枚举作为键
COLORS: dict[MinecraftColor, ColorInfo] = {
    MinecraftColor.BLACK: {
        "name_en": "black",
        "hex": "#000000",
        "dark_hex": "#000000",
        "rgb": (0, 0, 0),
        "dark_rgb": (0, 0, 0),
        "ansi": "\x1b[0;30m",
        "bedrock": True,
        "java": True,
        "code": "§0",
    },
    MinecraftColor.DARK_BLUE: {
        "name_en": "dark_blue",
        "hex": "#0000AA",
        "dark_hex": "#00002A",
        "rgb": (0, 0, 170),
        "dark_rgb": (0, 0, 42),
        "ansi": "\x1b[0;34m",
        "bedrock": True,
        "java": True,
        "code": "§1",
    },
    MinecraftColor.DARK_GREEN: {
        "name_en": "dark_green",
        "hex": "#00AA00",
        "dark_hex": "#002A00",
        "rgb": (0, 170, 0),
        "dark_rgb": (0, 42, 0),
        "ansi": "\x1b[0;32m",
        "bedrock": True,
        "java": True,
        "code": "§2",
    },
    MinecraftColor.DARK_AQUA: {
        "name_en": "dark_aqua",
        "hex": "#00AAAA",
        "dark_hex": "#002A2A",
        "rgb": (0, 170, 170),
        "dark_rgb": (0, 42, 42),
        "ansi": "\x1b[0;36m",
        "bedrock": True,
        "java": True,
        "code": "§3",
    },
    MinecraftColor.DARK_RED: {
        "name_en": "dark_red",
        "hex": "#AA0000",
        "dark_hex": "#2A0000",
        "rgb": (170, 0, 0),
        "dark_rgb": (42, 0, 0),
        "ansi": "\x1b[0;31m",
        "bedrock": True,
        "java": True,
        "code": "§4",
    },
    MinecraftColor.DARK_PURPLE: {
        "name_en": "dark_purple",
        "hex": "#AA00AA",
        "dark_hex": "#2A002A",
        "rgb": (170, 0, 170),
        "dark_rgb": (42, 0, 42),
        "ansi": "\x1b[0;35m",
        "bedrock": True,
        "java": True,
        "code": "§5",
    },
    MinecraftColor.GOLD: {
        "name_en": "gold",
        "hex": "#FFAA00",
        "dark_hex": "#402A00",
        "rgb": (255, 170, 0),
        "dark_rgb": (64, 42, 0),
        "ansi": "\x1b[0;33m",
        "bedrock": True,
        "java": True,
        "code": "§6",
    },
    MinecraftColor.GRAY: {
        "name_en": "gray",
        "hex": "#AAAAAA",
        "dark_hex": "#2A2A2A",
        "rgb": (170, 170, 170),
        "dark_rgb": (42, 42, 42),
        "ansi": "\x1b[0;37m",
        "bedrock": True,
        "java": True,
        "code": "§7",
    },
    MinecraftColor.DARK_GRAY: {
        "name_en": "dark_gray",
        "hex": "#555555",
        "dark_hex": "#151515",
        "rgb": (85, 85, 85),
        "dark_rgb": (21, 21, 21),
        "ansi": "\x1b[0;90m",
        "bedrock": True,
        "java": True,
        "code": "§8",
    },
    MinecraftColor.BLUE: {
        "name_en": "blue",
        "hex": "#5555FF",
        "dark_hex": "#15153F",
        "rgb": (85, 85, 255),
        "dark_rgb": (21, 21, 63),
        "ansi": "\x1b[0;94m",
        "bedrock": True,
        "java": True,
        "code": "§9",
    },
    MinecraftColor.GREEN: {
        "name_en": "green",
        "hex": "#55FF55",
        "dark_hex": "#153F15",
        "rgb": (85, 255, 85),
        "dark_rgb": (21, 63, 21),
        "ansi": "\x1b[0;92m",
        "bedrock": True,
        "java": True,
        "code": "§a",
    },
    MinecraftColor.AQUA: {
        "name_en": "aqua",
        "hex": "#55FFFF",
        "dark_hex": "#153F3F",
        "rgb": (85, 255, 255),
        "dark_rgb": (21, 63, 63),
        "ansi": "\x1b[0;96m",
        "bedrock": True,
        "java": True,
        "code": "§b",
    },
    MinecraftColor.RED: {
        "name_en": "red",
        "hex": "#FF5555",
        "dark_hex": "#3F1515",
        "rgb": (255, 85, 85),
        "dark_rgb": (63, 21, 21),
        "ansi": "\x1b[0;91m",
        "bedrock": True,
        "java": True,
        "code": "§c",
    },
    MinecraftColor.LIGHT_PURPLE: {
        "name_en": "light_purple",
        "hex": "#FF55FF",
        "dark_hex": "#3F153F",
        "rgb": (255, 85, 255),
        "dark_rgb": (63, 21, 63),
        "ansi": "\x1b[0;95m",
        "bedrock": True,
        "java": True,
        "code": "§d",
    },
    MinecraftColor.YELLOW: {
        "name_en": "yellow",
        "hex": "#FFFF55",
        "dark_hex": "#3F3F15",
        "rgb": (255, 255, 85),
        "dark_rgb": (63, 63, 21),
        "ansi": "\x1b[0;93m",
        "bedrock": True,
        "java": True,
        "code": "§e",
    },
    MinecraftColor.WHITE: {
        "name_en": "white",
        "hex": "#FFFFFF",
        "dark_hex": "#3F3F3F",
        "rgb": (255, 255, 255),
        "dark_rgb": (63, 63, 63),
        "ansi": "\x1b[0;97m",
        "bedrock": True,
        "java": True,
        "code": "§f",
    },
    MinecraftColor.MINECOIN_GOLD: {
        "name_en": "minecoin_gold",
        "hex": "#DDD605",
        "dark_hex": "#373501",
        "rgb": (221, 214, 5),
        "dark_rgb": (55, 53, 1),
        "ansi": "\x1b[0;38;2;221;214;5m",
        "bedrock": True,
        "java": False,
        "code": "§g",
    },
    MinecraftColor.MATERIAL_QUARTZ: {
        "name_en": "material_quartz",
        "hex": "#E3D4D1",
        "dark_hex": "#383534",
        "rgb": (227, 212, 209),
        "dark_rgb": (56, 53, 52),
        "ansi": "\x1b[0;38;2;227;212;209m",
        "bedrock": True,
        "java": False,
        "code": "§h",
    },
    MinecraftColor.MATERIAL_IRON: {
        "name_en": "material_iron",
        "hex": "#CECACA",
        "dark_hex": "#333232",
        "rgb": (206, 202, 202),
        "dark_rgb": (51, 50, 50),
        "ansi": "\x1b[0;38;2;206;202;202m",
        "bedrock": True,
        "java": False,
        "code": "§i",
    },
    MinecraftColor.MATERIAL_NETHERITE: {
        "name_en": "material_netherite",
        "hex": "#443A3B",
        "dark_hex": "#110E0E",
        "rgb": (68, 58, 59),
        "dark_rgb": (17, 14, 14),
        "ansi": "\x1b[0;38;2;68;58;59m",
        "bedrock": True,
        "java": False,
        "code": "§j",
    },
    MinecraftColor.MATERIAL_REDSTONE: {
        "name_en": "material_redstone",
        "hex": "#971607",
        "dark_hex": "#250501",
        "rgb": (151, 22, 7),
        "dark_rgb": (37, 5, 1),
        "ansi": "\x1b[0;38;2;151;22;7m",
        "bedrock": True,
        "java": False,
        "code": "§m",
    },
    MinecraftColor.MATERIAL_COPPER: {
        "name_en": "material_copper",
        "hex": "#B4684D",
        "dark_hex": "#2D1A13",
        "rgb": (180, 104, 77),
        "dark_rgb": (45, 26, 19),
        "ansi": "\x1b[0;38;2;180;104;77m",
        "bedrock": True,
        "java": False,
        "code": "§n",
    },
    MinecraftColor.MATERIAL_GOLD: {
        "name_en": "material_gold",
        "hex": "#DEB12D",
        "dark_hex": "#372C0B",
        "rgb": (222, 177, 45),
        "dark_rgb": (55, 44, 11),
        "ansi": "\x1b[0;38;2;222;177;45m",
        "bedrock": True,
        "java": False,
        "code": "§p",
    },
    MinecraftColor.MATERIAL_EMERALD: {
        "name_en": "material_emerald",
        "hex": "#11A036",
        "dark_hex": "#04280D",
        "rgb": (17, 160, 54),
        "dark_rgb": (4, 40, 13),
        "ansi": "\x1b[0;38;2;17;160;54m",
        "bedrock": True,
        "java": False,
        "code": "§q",
    },
    MinecraftColor.MATERIAL_DIAMOND: {
        "name_en": "material_diamond",
        "hex": "#2CBAA8",
        "dark_hex": "#0B2E2A",
        "rgb": (44, 186, 168),
        "dark_rgb": (11, 46, 42),
        "ansi": "\x1b[0;38;2;44;186;168m",
        "bedrock": True,
        "java": False,
        "code": "§s",
    },
    MinecraftColor.MATERIAL_LAPIS: {
        "name_en": "material_lapis",
        "hex": "#21497B",
        "dark_hex": "#08121E",
        "rgb": (33, 73, 123),
        "dark_rgb": (8, 18, 30),
        "ansi": "\x1b[0;38;2;33;73;123m",
        "bedrock": True,
        "java": False,
        "code": "§t",
    },
    MinecraftColor.MATERIAL_AMETHYST: {
        "name_en": "material_amethyst",
        "hex": "#9A5CC6",
        "dark_hex": "#261731",
        "rgb": (154, 92, 198),
        "dark_rgb": (38, 23, 49),
        "ansi": "\x1b[0;38;2;154;92;198m",
        "bedrock": True,
        "java": False,
        "code": "§u",
    },
    MinecraftColor.MATERIAL_RESIN: {
        "name_en": "material_resin",
        "hex": "#EB7114",
        "dark_hex": "#3B1D05",
        "rgb": (235, 114, 20),
        "dark_rgb": (59, 29, 5),
        "ansi": "\x1b[0;38;2;235;114;20m",
        "bedrock": True,
        "java": False,
        "code": "§v",
    },
}

FORMATS: dict[Formatting, FormatInfo] = {
    Formatting.BOLD: {
        "name_en": "bold",
        "ansi": "\x1b[1m",
        "bedrock": True,
        "java": True,
        "code": "§l",
    },
    Formatting.ITALIC: {
        "name_en": "italic",
        "ansi": "\x1b[3m",
        "bedrock": True,
        "java": True,
        "code": "§o",
    },
    Formatting.UNDERLINED: {
        "name_en": "underlined",
        "ansi": "\x1b[4m",
        "bedrock": False,
        "java": True,
        "code": "§n",
    },
    Formatting.STRIKETHROUGH: {
        "name_en": "strikethrough",
        "ansi": "\x1b[9m",
        "bedrock": False,
        "java": True,
        "code": "§m",
    },
    Formatting.OBFUSCATED: {
        "name_en": "obfuscated",
        "ansi": "\x1b[8m",
        "bedrock": True,
        "java": True,
        "code": "§k",
    },
    Formatting.RESET: {
        "name_en": "reset",
        "ansi": "\x1b[0m",
        "bedrock": True,
        "java": True,
        "code": "§r",
    },
}

# fmt: on
